#I.A
print("===========================================")
print("  ***          Hola soy Mat          ***  ")
print("===========================================")
nom=input("Por favor introduzca su nombrer: ")
print("Es un gutos",nom)
print("Dejame presentarme yo soy Mat y soy un mini programa informatico que te ayudara con tus tareas al largo de el dia")
tarea=input("Por favor dime que tareas quieres que te recuerde a lo largo del dia: ")
print("Tus tareas son: ",tarea)
print("Desea algo mas señor/señora?        ")
tarea2=input("")
print("Entendido señor: ",tarea2)
print ("Estas son todas sus tareas señor/señora:" ,tarea,tarea2)
print("Si necesita algo mas estare por aqui señor:")
tarea3=input("")
print("Nueva orden recibida señor/señora")
print("Se a añadido a la lista:",tarea3)

