#I.A
print("===========================================")
print("  ***          Hola soy Mat          ***  ")
print("===========================================")
nom=input("Por favor introduzca su nombrer: ")
print("Es un gutos",nom)
print("Dejame presentarme yo soy Mat y soy un mini programa informatico que te ayudara con tus tareas al largo de el dia")
tareas=input("Por favor dime que tareas quieres que te recuerde a lo largo del dia: ")
tarea1=input("")
tarea2=input("")
tarea3=input("")
tarea4=input("")
tarea5=input("")
tarea6=input("")
print("Entendido señor sus tareas son: " ,tareas, "," ,tarea1, "," ,tarea2, "," ,tarea3, "," ,tarea4, "," ,tarea5, "," ,tarea6,)
print("Señor si necesita algo mas por favor escriba que es lo que usted necesita que yo le rercuerde y le tendere de inmediato")
tarea7=input("")
tarea8=input("")
tarea9=input("")
tarea10=input("")
tarea11=input("")
tarea12=input("")
tarea13=input("")
tarea14=input("")
tarea15=input("")
tarea16=input("")
tarea17=input("")
tarea18=input("")
tarea19=input("")
tarea20=input("")
print("Entendido señor se a agradado a la lista de cosas por hacer:" "," ,tarea7, "," ,tarea8, "," ,tarea9, "," ,tarea10, "," ,tarea11, "," ,tarea12, "," ,tarea13, "," ,tarea14, "," ,tarea15, "," ,tarea16, "," ,tarea17, "," ,tarea18, "," ,tarea19, "," ,tarea20,)
print("Ahora su lista completa de tareas es: ",tareas, "," ,tarea1, "," ,tarea2, "," ,tarea3, "," ,tarea4, "," ,tarea5, "," ,tarea6,"," ,tarea7, "," ,tarea8, "," ,tarea9, "," ,tarea10, "," ,tarea11, "," ,tarea12, "," ,tarea13, "," ,tarea14, "," ,tarea15, "," ,tarea16, "," ,tarea17, "," ,tarea18, "," ,tarea19, "," ,tarea20,)
print("Señor esta seguro de que no necesita nada mas")
print("Estoy aqui para servirle señor si necesita algo mas no dude en solicitar mi ayuda")
ListaTareas=[,tareas, "," ,tarea1, "," ,tarea2, "," ,tarea3, "," ,tarea4, "," ,tarea5, "," ,tarea6,"," ,tarea7, "," ,tarea8, "," ,tarea9, "," ,tarea10, "," ,tarea11, "," ,tarea12, "," ,tarea13, "," ,tarea14, "," ,tarea15, "," ,tarea16, "," ,tarea17, "," ,tarea18, "," ,tarea19, "," ,tarea20,] 